//! A till's drawer and Z report as a pure fold over its rows.
//!
//! The server computes these in SQL (MadarRust `tills::handlers::
//! compute_system_cash`, `report_figures`, `tills::reconcile::
//! system_totals_by_method`); the till computes them offline from the ledger
//! rows the changefeed delivered (madar-core `ledger::report`, which loads the
//! rows from SQLite and calls this fold). The two are pinned by
//! `vectors/till_report_vectors.json`: SQL scenarios the backend runs, with
//! the rows as `/sync/pull` projects them and what the backend computed.
//!
//! Where the fold and the SQL could read an edge differently, this fold takes
//! the SERVER's reading (`vectors/till_edge_vectors.json`, generated by the
//! backend the same way):
//! - a payment method whose name is blank is dropped only when it is blank of
//!   SPACES (`btrim`), so a method named `"\t"` is kept, as the server keeps it;
//! - the org's fallback cash method is picked `ORDER BY (name = 'cash') DESC,
//!   is_active DESC, created_at` with Postgres's `NULLS LAST`.
//!
//! Every sale is ONE row whatever its sync state, so there is nothing to add
//! together and nothing to subtract.

use std::collections::{BTreeMap, BTreeSet};

use chrono::{DateTime, FixedOffset};

/// One tender of a sale (`order_payments`).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Leg {
    pub method: String,
    pub amount: i64,
    /// `COALESCE(op.is_cash, op.method = 'cash')`, resolved by the caller.
    pub is_cash: bool,
}

/// One sale of the till.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct Sale {
    /// What identifies the sale for `COUNT(DISTINCT order_id)`.
    pub key: String,
    pub status: String,
    pub payment_method: String,
    pub total: i64,
    pub tip: i64,
    pub tip_method: Option<String>,
    pub tip_is_cash: Option<bool>,
    pub legs: Vec<Leg>,
    pub tax: i64,
    pub service_charge: i64,
    /// The service charge was waived by someone.
    pub waived: bool,
    pub waived_amount: i64,
    /// Not yet on the server (only the till knows it).
    pub unsent: bool,
    /// The tax and service charge this sale's refunds took back, wherever
    /// they were issued.
    pub refunded_tax: i64,
    pub refunded_service_charge: i64,
}

impl Sale {
    /// `orders::TENDERED`: everything but a void counts in the drawer.
    pub fn tendered(&self) -> bool {
        self.status != "voided"
    }
    /// Sold: not voided and not refunded.
    pub fn sold(&self) -> bool {
        self.status != "voided" && self.status != "refunded"
    }
    /// `COALESCE(tip_is_cash, COALESCE(tip_payment_method, payment_method) = 'cash')`
    pub fn tip_cash(&self) -> bool {
        self.tip_is_cash
            .unwrap_or_else(|| self.tip_method.as_deref().unwrap_or(&self.payment_method) == "cash")
    }
    /// Cash this sale put in the drawer: its cash legs and a cash tip.
    pub fn cash_in(&self) -> i64 {
        let legs: i64 = self
            .legs
            .iter()
            .filter(|l| l.is_cash)
            .map(|l| l.amount)
            .sum();
        legs + if self.tip_cash() { self.tip } else { 0 }
    }
}

/// A drawer movement (`till_cash_movements`).
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct Movement {
    pub id: String,
    pub amount: i64,
    pub kind: String,
    pub corrects_id: Option<String>,
    /// The kind of the movement a correction reverses, when known.
    pub corrects_kind: Option<String>,
    pub note: String,
    pub moved_by_name: String,
    pub created_at: String,
}

impl Movement {
    /// The report bucket: a correction counts in the bucket of the movement it
    /// corrects; everything else in its own kind.
    pub fn bucket(&self) -> &str {
        match (self.kind.as_str(), self.corrects_kind.as_deref()) {
            ("correction", Some(corrected)) => corrected,
            (kind, _) => kind,
        }
    }
}

/// A movement as stored, before corrections are resolved.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct MovementRow {
    /// The till's own key for the row.
    pub key: String,
    /// The server's id, once it has one.
    pub server_id: Option<String>,
    pub amount: i64,
    pub kind: String,
    /// A correction names what it reverses by server id, or — queued before
    /// that movement synced — by its key.
    pub corrects_id: Option<String>,
    pub created_at: String,
    pub note: String,
    pub moved_by_name: String,
}

/// Resolve each correction's corrected kind and sort as the report lists them
/// (`ORDER BY created_at ASC`, compared as instants, ties by id).
pub fn movements(rows: Vec<MovementRow>) -> Vec<Movement> {
    let kind_of: BTreeMap<String, String> = rows
        .iter()
        .flat_map(|r| {
            let mut v = vec![(r.key.clone(), r.kind.clone())];
            if let Some(sid) = &r.server_id {
                v.push((sid.clone(), r.kind.clone()));
            }
            v
        })
        .collect();
    let mut out: Vec<Movement> = rows
        .into_iter()
        .map(|r| Movement {
            id: r.server_id.unwrap_or(r.key),
            amount: r.amount,
            corrects_kind: r.corrects_id.as_ref().and_then(|c| kind_of.get(c).cloned()),
            kind: r.kind,
            corrects_id: r.corrects_id,
            note: r.note,
            moved_by_name: r.moved_by_name,
            created_at: r.created_at,
        })
        .collect();
    out.sort_by(|a, b| {
        let ta = DateTime::parse_from_rfc3339(&a.created_at).ok();
        let tb = DateTime::parse_from_rfc3339(&b.created_at).ok();
        ta.cmp(&tb).then_with(|| a.id.cmp(&b.id))
    });
    out
}

/// A refund issued FROM this till.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct Refund {
    pub amount: i64,
    pub method: String,
    pub is_cash: bool,
    /// The tax and service charge this refund took back.
    pub tax: i64,
    pub service_charge: i64,
}

/// One refund of an order, for [`refund_splits`].
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct OrderRefund {
    pub key: String,
    pub amount: i64,
    /// The split the server recorded, once it has the refund.
    pub known: Option<(i64, i64)>,
}

/// The tax and service charge each refund of one order took back, in the
/// order given (issue order). A refund the server has seen carries its split;
/// one still queued is split with `madar_money::tax::refund_split` over the
/// refunds before it — the same cumulative arithmetic.
pub fn refund_splits(
    order_total: i64,
    order_tax: i64,
    order_service_charge: i64,
    refunds: &[OrderRefund],
) -> Vec<(String, (i64, i64))> {
    let mut before = 0;
    let mut out = Vec::with_capacity(refunds.len());
    for r in refunds {
        let split = r.known.unwrap_or_else(|| {
            madar_money::tax::refund_split(
                order_total,
                order_tax,
                order_service_charge,
                before,
                r.amount,
            )
        });
        before += r.amount;
        out.push((r.key.clone(), split));
    }
    out
}

/// An org payment method as the close preview needs it.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct Method {
    pub id: String,
    pub name: String,
    pub is_cash: bool,
    pub is_active: bool,
    /// RFC 3339; `None` when the row carried none.
    pub created_at: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PaymentLine {
    pub payment_method: String,
    pub is_cash: bool,
    pub total: i64,
    pub order_count: i64,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MethodTotal {
    pub method: String,
    pub payment_method_id: Option<String>,
    pub is_cash: bool,
    pub system_total: i64,
    pub order_count: i64,
}

/// Everything the backend's report says about a till's money.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Figures {
    pub system_cash: i64,
    pub expected_cash: i64,
    pub payment_summary: Vec<PaymentLine>,
    pub total_payments: i64,
    pub voided_amount: i64,
    pub net_payments: i64,
    pub total_tips: i64,
    pub cash_tips: i64,
    pub non_cash_tips: i64,
    pub cash_movements_in: i64,
    pub cash_movements_out: i64,
    pub safe_drops: i64,
    pub cash_adjustments: i64,
    pub cash_movements_net: i64,
    pub refunds_issued_count: i64,
    pub refunds_issued_amount: i64,
    pub refunds_issued_cash: i64,
    pub cash_in_refunded_sales: i64,
    /// Tax / service charge on the sold sales, less what their refunds took back.
    pub total_tax: i64,
    pub total_service_charge: i64,
    pub refunds_issued_tax: i64,
    pub refunds_issued_service_charge: i64,
    pub service_charge_waived_count: i64,
    pub service_charge_waived_amount: i64,
    pub close_methods: Vec<MethodTotal>,
}

/// The drawer: float + cash tenders + cash tips (not voided) + movements −
/// cash refunds issued from this till. `compute_system_cash`.
pub fn system_cash(opening: i64, sales: &[Sale], moves: &[Movement], refunds: &[Refund]) -> i64 {
    let tendered_cash: i64 = sales
        .iter()
        .filter(|o| o.tendered())
        .map(Sale::cash_in)
        .sum();
    let moves_net: i64 = moves.iter().map(|m| m.amount).sum();
    let refunds_cash: i64 = refunds.iter().filter(|r| r.is_cash).map(|r| r.amount).sum();
    opening + tendered_cash + moves_net - refunds_cash
}

/// The report for one till.
///
/// `closing_cash_system` is the drawer figure frozen at close, when the till
/// is closed: the server recomputes that snapshot only when a queued sale lands
/// late, so the sales still on their way are added on top of it — and nothing
/// else is.
pub fn fold(
    opening: i64,
    closing_cash_system: Option<i64>,
    sales: &[Sale],
    moves: &[Movement],
    refunds: &[Refund],
    methods: &[Method],
) -> Figures {
    let system_cash = system_cash(opening, sales, moves, refunds);
    let moves_net: i64 = moves.iter().map(|m| m.amount).sum();
    let refunds_cash: i64 = refunds.iter().filter(|r| r.is_cash).map(|r| r.amount).sum();

    // Payment summary over SOLD orders, grouped by method.
    let mut by_method: BTreeMap<String, (bool, i64, BTreeSet<String>)> = BTreeMap::new();
    for o in sales.iter().filter(|o| o.sold()) {
        for l in &o.legs {
            let e = by_method
                .entry(l.method.clone())
                .or_insert((false, 0, BTreeSet::new()));
            e.0 |= l.is_cash;
            e.1 += l.amount;
            e.2.insert(o.key.clone());
        }
    }
    let payment_summary: Vec<PaymentLine> = by_method
        .into_iter()
        .map(|(m, (c, t, orders))| PaymentLine {
            payment_method: m,
            is_cash: c,
            total: t,
            order_count: orders.len() as i64,
        })
        .collect();
    let total_payments: i64 = payment_summary.iter().map(|p| p.total).sum();
    let total_tips: i64 = sales.iter().filter(|o| o.sold()).map(|o| o.tip).sum();
    let cash_tips: i64 = sales
        .iter()
        .filter(|o| o.sold() && o.tip_cash())
        .map(|o| o.tip)
        .sum();
    let voided_amount: i64 = sales
        .iter()
        .filter(|o| o.status == "voided")
        .map(|o| o.total)
        .sum();
    let bucket_total = |b: &str| -> i64 {
        moves
            .iter()
            .filter(|m| m.bucket() == b)
            .map(|m| m.amount)
            .sum()
    };
    let cash_in_refunded_sales: i64 = sales
        .iter()
        .filter(|o| o.status == "refunded")
        .map(Sale::cash_in)
        .sum();
    let sold = || sales.iter().filter(|o| o.sold());
    let total_tax: i64 = sold().map(|o| o.tax - o.refunded_tax).sum();
    let total_service_charge: i64 = sold()
        .map(|o| o.service_charge - o.refunded_service_charge)
        .sum();

    let expected_cash = match closing_cash_system {
        Some(snap) => {
            snap + sales
                .iter()
                .filter(|o| o.unsent && o.tendered())
                .map(Sale::cash_in)
                .sum::<i64>()
        }
        None => system_cash,
    };

    Figures {
        system_cash,
        expected_cash,
        net_payments: total_payments,
        total_payments,
        voided_amount,
        total_tips,
        cash_tips,
        non_cash_tips: total_tips - cash_tips,
        cash_movements_in: bucket_total("pay_in"),
        cash_movements_out: -bucket_total("pay_out"),
        safe_drops: -bucket_total("safe_drop"),
        cash_adjustments: bucket_total("correction"),
        cash_movements_net: moves_net,
        refunds_issued_count: refunds.len() as i64,
        refunds_issued_amount: refunds.iter().map(|r| r.amount).sum(),
        refunds_issued_cash: refunds_cash,
        cash_in_refunded_sales,
        total_tax,
        total_service_charge,
        refunds_issued_tax: refunds.iter().map(|r| r.tax).sum(),
        refunds_issued_service_charge: refunds.iter().map(|r| r.service_charge).sum(),
        service_charge_waived_count: sold().filter(|o| o.waived).count() as i64,
        service_charge_waived_amount: sold().map(|o| o.waived_amount).sum(),
        payment_summary,
        close_methods: close_methods(sales, refunds, expected_cash, methods),
    }
}

/// The server's blank test: `btrim(method) <> ''` strips SPACES only.
pub fn is_blank_method(method: &str) -> bool {
    method.trim_matches(' ').is_empty()
}

/// The org's fallback cash method: `ORDER BY (name = 'cash') DESC, is_active
/// DESC, created_at LIMIT 1` over the cash-flagged methods, a missing
/// `created_at` sorting LAST as Postgres sorts a NULL.
pub fn fallback_cash_method(methods: &[Method]) -> Option<&Method> {
    let at = |m: &Method| -> Option<DateTime<FixedOffset>> {
        m.created_at
            .as_deref()
            .and_then(|t| DateTime::parse_from_rfc3339(t).ok())
    };
    let mut cash: Vec<&Method> = methods.iter().filter(|m| m.is_cash).collect();
    cash.sort_by(|a, b| {
        (b.name == "cash")
            .cmp(&(a.name == "cash"))
            .then(b.is_active.cmp(&a.is_active))
            .then_with(|| match (at(a), at(b)) {
                (Some(x), Some(y)) => x.cmp(&y),
                (Some(_), None) => std::cmp::Ordering::Less,
                (None, Some(_)) => std::cmp::Ordering::Greater,
                (None, None) => std::cmp::Ordering::Equal,
            })
    });
    cash.first().copied()
}

/// Every method used on the till, with the system's total for it
/// (`system_totals_by_method`). Cash is ONE row, first, `system_total =
/// expected_cash`, named after the cash-flagged method used on the till (the
/// literal `cash` preferred), else the org's first cash method, else `cash`.
pub fn close_methods(
    sales: &[Sale],
    refunds: &[Refund],
    expected_cash: i64,
    methods: &[Method],
) -> Vec<MethodTotal> {
    // used: tendered legs, tendered non-zero tips, and refunds (negative).
    let mut by_method: BTreeMap<String, (bool, i64, BTreeSet<String>)> = BTreeMap::new();
    let mut add = |m: &str, cash: bool, amount: i64, order: Option<&str>| {
        if is_blank_method(m) {
            return;
        }
        let e = by_method
            .entry(m.to_string())
            .or_insert((false, 0, BTreeSet::new()));
        e.0 |= cash;
        e.1 += amount;
        if let Some(o) = order {
            e.2.insert(o.to_string());
        }
    };
    for o in sales.iter().filter(|o| o.tendered()) {
        for l in &o.legs {
            add(&l.method, l.is_cash, l.amount, Some(&o.key));
        }
        if o.tip != 0 {
            let m = o
                .tip_method
                .clone()
                .unwrap_or_else(|| o.payment_method.clone());
            add(&m, o.tip_cash(), o.tip, None);
        }
    }
    for r in refunds {
        add(&r.method, r.is_cash, -r.amount, None);
    }
    let id_of = |name: &str| {
        methods
            .iter()
            .find(|m| m.name == name)
            .map(|m| m.id.clone())
    };
    let mut cash_name: Option<String> = None;
    let mut cash_orders = 0i64;
    let mut out = Vec::new();
    for (method, (is_cash, total, orders)) in by_method {
        if is_cash {
            cash_orders += orders.len() as i64;
            if cash_name.is_none() || method == "cash" {
                cash_name = Some(method);
            }
        } else {
            out.push(MethodTotal {
                payment_method_id: id_of(&method),
                method,
                is_cash: false,
                system_total: total,
                order_count: orders.len() as i64,
            });
        }
    }
    let (method, payment_method_id) = match cash_name {
        Some(c) => {
            let id = id_of(&c);
            (c, id)
        }
        None => match fallback_cash_method(methods) {
            Some(m) => (m.name.clone(), Some(m.id.clone())),
            None => ("cash".to_string(), None),
        },
    };
    out.insert(
        0,
        MethodTotal {
            method,
            payment_method_id,
            is_cash: true,
            system_total: expected_cash,
            order_count: cash_orders,
        },
    );
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn cash(id: &str, name: &str, active: bool, at: Option<&str>) -> Method {
        Method {
            id: id.into(),
            name: name.into(),
            is_cash: true,
            is_active: active,
            created_at: at.map(str::to_string),
        }
    }

    #[test]
    fn a_method_without_a_creation_time_is_picked_last_like_postgres() {
        let ms = [
            cash("a", "Cash drawer", true, None),
            cash("b", "Petty", true, Some("2026-01-01T00:00:00Z")),
        ];
        assert_eq!(fallback_cash_method(&ms).unwrap().id, "b");
    }

    #[test]
    fn only_spaces_make_a_method_blank() {
        assert!(is_blank_method("   "));
        assert!(is_blank_method(""));
        assert!(!is_blank_method("\t"));
        assert!(!is_blank_method("\u{a0}"));
    }

    #[test]
    fn queued_refunds_split_cumulatively_after_known_ones() {
        let out = refund_splits(
            5700,
            700,
            0,
            &[
                OrderRefund {
                    key: "b".into(),
                    amount: 1234,
                    known: Some((152, 0)),
                },
                OrderRefund {
                    key: "a".into(),
                    amount: 333,
                    known: None,
                },
            ],
        );
        assert_eq!(out[0], ("b".to_string(), (152, 0)));
        assert_eq!(
            out[1].1,
            madar_money::tax::refund_split(5700, 700, 0, 1234, 333)
        );
    }
}
